version: 0.0.1
name: 'Offline Met Studies'

input:
  files:
      # Single Muons
      # -   root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/SingleMuon/Collision2017-wRECO-l1t-integration-v96p27/SingleMuon/crab_Collision2017-wRECO-l1t-integration-v96p27__SingleMuon/170818_102121/000*/L1Ntuple_*.root
      # -   root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/SingleMuon/Fill*/Collision2017-wRECO-l1t-integration-v96p27_CaloMode/SingleMuon/crab_Collision2017-wRECO-l1t-integration-v96p27_CaloMode__SingleMuon/*/0000/L1Ntuple_*root
      # -   root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/SingleMuon/Collision2017-wRECO-l1t-integration-v96p27_NoPUS/SingleMuon/crab_Collision2017-wRECO-l1t-integration-v96p27_NoPUS__SingleMuon/170828_103245/0000/L1Ntuple*.root
       -   root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/wRECO-l1t-v96p27/SingleMuon/crab_wRECO-l1t-v96p27__Run*/*/0001/L1Ntuple_*root
      # Zero Bias
      # -  root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/ZeroBias/Fill6*/Collision2017-noRECO-l1t-integration-96p27_NoPUS/ZeroBias/crab_Collision2017-noRECO-l1t-integration-96p27_NoPUS__ZeroBias_Run2017C/*/0000/L1Ntuple_*root
      # -  root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/ZeroBias/Collision2017-noRECO-l1t-integration-96p20/ZeroBias/crab_Collision2017-noRECO-l1t-integration-96p20__ZeroBias_Run2017C/170726_094745/0000/*root
  sample:
    name: Data
    title: 2017 Data
  trigger:
    # name: ZeroBias
    # title: Zero Bias
    name: SingleMu
    title: Single Muon
  pileup_file: ""
  run_number: 6XXX

analysis:
  do_fit: True
  pu_type: 0PU24,25PU49,50PU
  pu_bins: [0,25,50,999]
  thresholds:
    HTT: [160, 220, 280, 340, 400]
    HTT_Emu: [160, 218, 273, 333, 333]
    MHT: [40, 60, 80, 100, 120]
    MHT_Emu: [40, 60, 80, 100, 120]
    MET_HF: [40, 60, 80, 100, 120]
    MET_HF_Emu: [40, 60, 80, 99, 105]
    MET: [40, 60, 80, 100, 120]
    MET_Emu: [40, 60, 80, 99, 111]
    MET_PF: [40, 60, 80, 100, 120]
    MET_PF_Emu: [40, 60, 80, 99, 111]
    MET_PF_NoMu: [40, 60, 80, 100, 120]
    MET_PF_NoMu_Emu: [40, 60, 80, 99, 111]
    MET_PF_HF: [40, 60, 80, 100, 120]
    MET_PF_HF_Emu: [40, 60, 80, 99, 105]
    MET_PF_NoMu_HF: [40, 60, 80, 100, 120]
    MET_PF_NoMu_HF_Emu: [40, 60, 80, 99, 105]
    singlel1JetEt: [35, 60, 90, 140, 180]
    singlel1JetEt_Emu: [21, 44, 68, 103, 120]
    doublel1JetEt: [35, 60, 90, 140, 180]
    doublel1JetEt_Emu: [22, 45, 71, 106, 121]
    triplel1JetEt: [35, 60, 90, 140, 180]
    triplel1JetEt_Emu: [22, 47, 74, 108, 122]
    quadl1JetEt: [35, 60, 90, 140, 180]
    quadl1JetEt_Emu: [21, 48, 75, 109, 122]
  analyzers:
     - cmsl1t.analyzers.HW_Emu_constant_rate_turnons
  modifiers: []
  progress_bar:
    report_every: 1000

output:
  template:
     - output/constant_rate_turnons
     - "{date}_Fill-{run_number}_{sample_name}_{trigger_name}"
