#!/usr/bin/env bash
# alias bjobs='echo "JOBID     USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME";echo "113     user1   PEND  normal     hostA                   myjob     Jun 17 16:15"'
job_id=$1
echo "JOBID     USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME"
echo "${job_id}     user2   RUN   normal     hostA       hostA       myjob     Jun 14 15:13"
